M48
; DRILL file {KiCad (6.0.9)} date Tue Dec 20 19:16:25 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-20T19:16:25+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.0157Y-0.8972
X0.0157Y-1.1248
X0.0157Y-1.9846
X0.0157Y-2.2122
T0
M30
