M48
; DRILL file {KiCad (6.0.9)} date Mon Jan  9 11:29:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-09T11:29:15+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.0157Y-0.8972
X0.0157Y-1.1248
X0.0157Y-1.9846
X0.0157Y-2.2122
T0
M30
